### PR TITLE
tie alias creation to premium subscriptions

### LINKED ISSUE #645: Integrate alias feature with paid tiers
**Is your feature request related to a problem? Please describe.**

When #595 was merged, it didn't include gating the Aliases feature on a paid subscription. This ticket attempts to answer open questions related to that.

**Questions**

- Should the `Alias` tab on the settings page be visible or absent when a user doesn't have a paid subscription?
- If the Alias tab is visible, what copy should it have? "This is only available for paid users. Plz upgrade."
- For "personal server" mode or self-hosted, should this feature be configurable? As in, an admin can say "all users get it or none regardless of Stripe"? If so, we need a config flag for that

### PR DESCRIPTION
**Pull request by brassy-endomorph**
fixes #645

- split `utils.py` into smaller modules to get rid of circular imports
- add `ALIAS_MODE` config
- gate number of aliases on `ALIAS_MODE` and/or premium status

### CODE REVIEW

**Comment by glenn-sorrentino** [comment]
Subscribed users get 100 aliases. Single-tenant is unlimited. Free is none.

**Comment by glenn-sorrentino** [comment]
Will leave comments while testing:

First - In the screenshot, I have not subscribed and have no aliases. the `To:` string in the user's inbox is only applicable if they have at least one alias. 

Screenshot 2024-10-17 at 9 30 01 AM

**Comment by glenn-sorrentino** [comment]
Other than the comment above, the functionality on the front-end works well!

**Comment by glenn-sorrentino** [comment]
Noticing during the cancel
Screenshot 2024-10-17 at 9 39 30 AM
 subscription flow that the page isn't redirecting back to the premium page...

**Comment by brassy-endomorph** [comment]
>  [subscription flow that the page isn't redirecting back to the premium page...](https://github.com/scidsg/hushline/pull/699#issuecomment-2420019089)
@micahflee you recognize this?

**Comment by glenn-sorrentino** [comment]
Also when I click "Cancel Now" I'm directed to the disable auto-renew page, but that's a different feature from canceling...

cancel-sub

**Comment by brassy-endomorph** [comment]
Those sound like bugs for other tickets because they're not directly related to this PR and shoulnd't be addressed here. That will just make this ticket massive and more difficult to get merged. I can do that in a followup too, but it's not really relevant to the changeset I'm proposing.

**Comment by glenn-sorrentino** [comment]
> Those sound like bugs for other tickets because they're not directly related to this PR and shoulnd't be addressed here. That will just make this ticket massive and more difficult to get merged. I can do that in a followup too, but it's not really relevant to the changeset I'm proposing.

By "those", which of the above do you mean?

**Comment by brassy-endomorph** [comment]
https://github.com/scidsg/hushline/pull/699#issuecomment-2420027144

and 

https://github.com/scidsg/hushline/pull/699#issuecomment-2420019089

Canceling / disabling autorenew should be separate tickets

**Review by glenn-sorrentino — APPROVED** [review]

**Pull request merged**
