### PR TITLE
Runs all scripts through shfmt

### PR DESCRIPTION
**Pull request by sts10**
Don't know how important this is to the project as a whole, but I thought it might be helpful to run all the shell scripts in `/scripts` through [shfmt](https://github.com/mvdan/sh) (using 4 spaces for indents). 

I'm not able to run/test these formatted scripts, so there is a chance that this formatting may have caused new errors. But I hope not!

### CODE REVIEW

**Comment by glenn-sorrentino** [comment]
Thank you @sts10! Testing now!

**Comment by glenn-sorrentino** [comment]
Tested on VPS + Pi with no errors.

**Comment by glenn-sorrentino** [comment]
Thanks for your contribution, @sts10! Let me know if you'd like to get more involved with the product!

**Comment by sts10** [comment]
>  Let me know if you'd like to get more involved with the product!

I'd love to! Any suggestions on where to get my hands dirty? I don't have access to a Raspberry Pi atm, but I'll see if I can run through the installation on an old laptop running Ubuntu? (I'm a bit rusty!)

**Comment by glenn-sorrentino** [comment]
Can you shoot an email to glenn@scidsg.org?

**Pull request merged**
